services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgres://postgres@postgres:5432/monnaie
  postgres:
    image: postgres:14
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=monnaie
    volumes:
      - pgdata:/var/lib/postgresql/data
      
volumes:
  pgdata: